source 'https://rubygems.org'

gem 'sinatra', '~> 1.4'
gem 'thin', '~> 1.6'
gem 'activerecord', '~> 4.2'
gem 'json', '~> 1.8'

group :development do
  gem 'sqlite3', '~> 1.3'
  gem 'rake', '~> 10.4'
  gem 'rubocop', '~> 0.31'
  gem 'pry', '~> 0.10'
end

group :production do
  gem 'pg', '~> 0.18'
end

group :test do
  gem 'rspec', '~> 3.2'
end

group :documentation do
  gem 'yard', '~> 0.8'
  gem 'yard-rspec', '~> 0.1'
  gem 'kramdown', '~> 1.7'
end
